package com.catering.constant;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class Constants {

	public static final String COMPANY_ID = "companyId";
	public static final String USER_ID = "userId";
	public static final String TENANT = "tenant";
	public static final String TOKEN = "token";
	public static final String COMPANY_USER_TABLE_NAME = "company_user";
	public static final String CURRENT_PAGE = "currentPage";
	public static final String SIZE_PER_PAGE = "sizePerPage";
	public static final String SORT_BY = "sortBy";
	public static final String SORT_DIRECTION = "sortDirection";
	public static final String QUERY = "query";
	public static final String IDS = "IDs";
	public static final String RAW_MATERIAL_ID = "rawMaterialId";
	public static final String MENU_ITEM_ID = "menuItemId";
	public static final String EXIST_ID = "existId";
	public static final String AGENCY = "agency";
	public static final String CONTACT_AGENCY_ID = "contactAgencyId";
	public static final String ORDER_DATE_REF = "orderDateRef";
	public static final String ORDER_TIME_REF = "orderTimeRef";
	public static final String TIME_PERIOD = "timePeriod";
	public static final String FUNCTION_NAME = "functionName";
	public static final String CONTACT_ID = "contactId";
	public static final String CONTACT_NAME = "contactName";
	public static final String SUPPLIER_ID = "supplierId";
	public static final String SUPPLIER_NAME = "supplierName";
	public static final String MENU_ITEM_GROUP = "menuItemGroup";
	public static final String IMAGE = "image";
	public static final String IMG = "img";
	public static final String LOGO = "logo";
	public static final String QRCODE = "qRCode";
	private static final String REPORT = "report/";
	public static final String REPORT_BACKGROUND = REPORT + "background";
	public static final String GENERAL_REPORT_BACKGROUND = REPORT + "general-report-background";
	public static final String REPORT_FRAME = REPORT + "frame";
	public static final String BACKGROUND_LAST = REPORT + "background-last";
	public static final String IMAGE_MENU_REPORT_BACKGROUND = REPORT + "image-menu-report-background";
	public static final String REPORT_TERMS_AND_CONDITIONS = REPORT + "termsAndConditions";
	public static final String REPORT_EXCLUSIVE_IMAGE = REPORT + "exclusive-design";
	public static final String REPORT_SLOGAN_MENU_DESIGN = REPORT + "menu-with-slogan-design";
	public static final String REPORT_PACKAGE_BACKGROUND = REPORT + "package-background";
	public static final String REPORT_TABLE_MENU_BACKGROUND = REPORT + "table-menu-background";
	public static final String REPORT_TABLE_MENU_UNDERLINE_IMAGE = REPORT + "table-menu-item-category-underline";
	public static final String SIDEBAR_CACHE = "#uniqueCode";
	public static final String SIDEBAR_ALL_MENUS_CACHE = "#sidebarAllMenuCache";
	public static final String USER_RIGHTS_CACHE = "#userRightsCache";
	public static final String REPORT_RIGHTS_CACHE = "#reportUserRightsCache";
	public static final String COMPANY_LOGO_CACHE = "#companyLogoCache";
	public static final int ORDER_TYPE_FOR_CHEF_LABOUR = 1;
	public static final int ORDER_TYPE_FOR_OUT_SIDE_LABOUR = 2;
	public static final String JASPER = "jasper";
	public static final String GENERAL_REPORT = "general-report";
	public static final Long OUTSIDE_CONTACT_CATEGORY = 4l;
	public static final Long CHEF_LABOUR_CONTACT_CATEGORY = 5l;
	public static final Long LABOUR_CONTACT_CATEGORY = 2l;
	public static final Long CATERING_PREFERENCES_ID = 1L;
	public static final String CURRENT_DATE = "CURRENT_DATE";
	public static final String NOTIFICATION_ID = "notificationId";
	public static final String LANGUAGE_DEFAULT = "default";
	public static final String LANGUAGE_PREFER = "prefer";
	public static final String LANGUAGE_SUPPORTIVE = "supportive";
	public static final String SHYAM_CATERERS_SURAT_TENANT = "0d2115b6-03a3-46e9-bd73-f06dbd49ec06";
	public static final String GOKUL_CATERERS = "160a1c1e-1682-47cf-9f04-a453fcdc4acb";
	public static final String KARUNA_CATERERS_TENANT = "b6846c41-38cd-4860-8c30-aee8e63ead35";
	public static final String SHYAM_CATERERS_AMRELI_TENANT = "926709e1-5c24-46a3-8f42-d44bae6d2a0b";
	public static final String RAJA_CATERERS_TENANT = "b9d2f7fe-9530-4e2d-b284-906ae92772ad";
	public static final String SATHIYA_CATERERS_TENANT = "61989ee4-c029-41e4-b019-c13b1488ffbd";
	public static final String PANCHAMRUT_CATERERS_TENANT = "79652d42-4934-4fd4-84a6-41a171d928c9";
	public static final String ELITE_CATERERS_TENANT = "708a9236-a6ea-47bd-b2d3-5aab51208cb6";
	public static final String SHREE_RAJ_CATERING = "bbf691aa-1ca1-485c-b424-4a38ec68f71d";
	public static final String JASRAJ_UTTAM_CATERERS = "1defdb6d-53a4-437f-8a21-f9fbea727adf";
	public static final String BRIJ_BHOG_CATERERS = "f51cf855-0e00-43fe-b143-f9c250a7c448";
	public static final String YOGESHWAR_CATERERS = "90568b7d-e9f1-423a-b9e8-168a0d7916e7";
	public static final String VISHAL_CATERERS = "1fa332a1-0aa0-48eb-9ce4-6c83af79f427";
	public static final String BR_CATERERS = "7eb2b410-e714-4a73-b757-de60a4263277";
	public static final String PANDYA_CATERERS = "ee4f0e8b-9342-4dc4-9c07-5d3d7788b895";
	public static final String SURTI_CATERERS_TENANT = "308e5624-1e80-483a-ac08-0d804d46976e";
	public static final String LOGO_HORIZONTAL = "logoHorizontal";
	public static final String LOGO_HORIZONTAL_WHITE = "logoHorizontalWhite";
	public static final String LOGO_VERTICAL = "logoVertical";
	public static final String FAVICON = "favicon";
	public static final byte REPORT_SIZE_12 = 12;
	public static final byte REPORT_SIZE_16 = 16;
	public static final Long ORDER_STATUS_CONFIRM = 2l;
	public static final String REPORT_WATERMARK = REPORT + "watermark";
	public static final Long PURCHASE_ORDER_SUPPILER_CATEGORY_TYPE_ID = 3l;

	public static final String REPORT_SPOON = REPORT + "spoon";
	public static final String REPORT_RUPPES = REPORT + "ruppes";
	public static final String REPORT_PERSON = REPORT + "person";
	public static final String REPORT_DATE = REPORT + "date";
	public static final String REPORT_BACKGROUND_LINE = REPORT + "background-line";
	public static final String REPORT_CALL = REPORT + "call";
	public static final String REPORT_WHATSAPP = REPORT + "whatsapp";
	public static final String REPORT_ADDRESS = REPORT + "address";

}