package com.catering.constant;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class ReportNameConstant {

	// Menu preparation
	public static final String CUSTOM_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.CUSTOM-MENU-REPORT";
	public static final String SIMPLE_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.SIMPLE-MENU-REPORT";
	public static final String EXCLUSIVE_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.EXCLUSIVE-MENU-REPORT";
	public static final String SLOGAN_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.SLOGAN-MENU-REPORT";
	public static final String PREMIUM_IMAGE_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.PREMIUM-IMAGE-MENU-REPORT";
	public static final String IMAGE_REPORT_WITH_MENU = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.IMAGE-REPORT-WITH-MENU";
	public static final String IMAGE_AND_SLOGAN_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.IMAGE-AND-SLOGAN-MENU-REPORT";
	public static final String IMAGE_MENU_CATEGORY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.IMAGE-MENU-CATEGORY-REPORT";
	public static final String TWO_LANGUAGE_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.TWO-LANGUAGE-MENU-REPORT";
	public static final String MANAGER_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.MANAGER-MENU-REPORT";
	public static final String INSTRUCTION_MENU_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.INSTRUCTION-MENU-REPORT";

	// Menu Allocation
	public static final String MENU_WITH_QUANTITY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.MENU-WITH-QUANTITY-REPORT";
	public static final String MENU_WITH_OUT_QUANTITY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.MENU-WITH-OUT-QUANTITY-REPORT";

	// Raw Material Allocation
	public static final String MENU_ITEM_WISE_RAW_MATERIAL_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.MENU-ITEM-WISE-RAW-MATERIAL-REPORT";
	public static final String DETAILED_RAW_MATERIAL_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.DETAILED-RAW-MATERIAL-REPORT";
	public static final String TOTAL_RAW_MATERIAL_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.TOTAL-RAW-MATERIAL-REPORT";
	public static final String TOTAL_RAW_MATERIAL_WITH_CATEGORY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.TOTAL-RAW-MATERIAL-WITH-CATEGORY-REPORT";
	public static final String SUPPLIER_WISE_RAW_MATERIAL_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.SUPPLIER-WISE-RAW-MATERIAL-REPORT";
	public static final String ORDER_FILE_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.ORDER-FILE-REPORT";
	public static final String TIME_WISE_RAW_MATERIAL_A4_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.TIME-WISE-RAW-MATERIAL-A4-REPORT";
	public static final String TIME_WISE_RAW_MATERIAL_A5_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.TIME-WISE-RAW-MATERIAL-A5-REPORT";
	public static final String TIME_WISE_RAW_MATERIAL_A6_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.TIME-WISE-RAW-MATERIAL-A6-REPORT";
	public static final String CHEF_LABOUR_WISE_RAW_MATERIAL_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.CHEF-LABOUR-WISE-RAW-MATERIAL-REPORT";
	public static final String CHEF_LABOUR_SUPPLIER_WISE_RAW_MATERIAL_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.CHEF-LABOUR-SUPPLIER-WISE-RAW-MATERIAL-REPORT";

	// Labour and agency
	public static final String BOOKING_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.BOOKING-REPORT";
	public static final String CHEF_LABOUR_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.CHEF-LABOUR-REPORT";
	public static final String CHEF_LABOUR_CHITHHI_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.CHEF-LABOUR-CHITHHI-REPORT";
	public static final String OUTSIDE_AGENCY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.OUTSIDE-AGENCY-REPORT";
	public static final String OUTSIDE_AGENCY_CHITHHI_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.OUTSIDE-AGENCY-CHITHHI-REPORT";
	public static final String LABOUR_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.LABOUR-REPORT";
	public static final String LABOUR_CHITHHI_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.LABOUR-CHITHHI-REPORT";

	// General fix and crockery
	public static final String GENERAL_FIX_WITH_QUANTITY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.GENERAL-FIX-WITH-QUANTITY-REPORT";
	public static final String GENERAL_FIX_WITHOUT_QUANTITY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.GENERAL-FIX-WITHOUT-QUANTITY-REPORT";
	public static final String CROCKERY_WITH_QUANTITY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.CROCKERY-WITH-QUANTITY-REPORT";
	public static final String CROCKERY_WITHOUT_QUANTITY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.CROCKERY-WITHOUT-QUANTITY-REPORT";
	public static final String KITCHEN_CATEGORY_WITH_QTY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.KITCHEN-CATEGORY-WITH-QTY-REPORT";
	public static final String KITCHEN_CATEGORY_WITHOUT_QTY_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.KITCHEN-CATEGORY-WITHOUT-QTY-REPORT";

	public static final String DISH_COUNTING_REPORT = "ORDER-EXECUTION.ORDER-BOOKING-REPORTS.FEEDBACK-REPORT";
}